name: LosMundosDeCalderoom
favicon: null
layout_spectrum: 0.6472
typography_spectrum: 0.37054
title: La magia esta dentro de ti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#412e1f'
    - '#040500'
    - '#e4d2a4'
    - '#5f6750'
    - '#b83f07'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
