name: LosMundosDeCalderoom
favicon: null
layout_spectrum: 0.29922
typography_spectrum: 0.84375
title: La magia esta dentro de ti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68882b'
    - '#afc39d'
    - '#394438'
    - '#c7763b'
    - '#e7e3cd'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
