name: LosMundosDeCalderoom
favicon: null
layout_spectrum: 0.20409
typography_spectrum: 0.28144
title: La magia esta dentro de ti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01216c'
    - '#657dbb'
    - '#fff2e2'
    - '#114e87'
    - '#bfacb2'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
