name: LosMundosDeCalderoom
favicon: null
layout_spectrum: 0.46145497378893197
typography_spectrum: 0.8991352999582887
title: La magia esta dentro de ti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3352893372066319
  lightness: 0.37050396273843944
  saturation: 0.18303666193969548
  rhythmicContrast: 0.1179508927743882
purpose: []
